# Generated by Django 4.0.3 on 2022-04-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0002_submission_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
