# Generated by Django 4.0.3 on 2022-04-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment_votes_alter_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
