# Generated by Django 4.0.3 on 2022-04-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='points',
        ),
    ]
