# Generated by Django 4.0.3 on 2022-04-18 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_alter_user_options_remove_user_karma'),
        ('news', '0009_commentvote_alter_vote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.comment'),
        ),
        migrations.AddField(
            model_name='vote',
            name='type',
            field=models.ForeignKey(default='Submissions', on_delete=django.db.models.deletion.RESTRICT, to='news.actiontype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(related_name='comment_votes', through='news.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('submission', 'user'), ('comment', 'user')},
        ),
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
