# Generated by Django 4.0.3 on 2022-04-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_vote_comment_vote_type_alter_comment_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='news.actiontype'),
        ),
    ]
