# Generated by Django 4.0.3 on 2022-04-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
