# Generated by Django 4.0.3 on 2022-04-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
