# Generated by Django 4.0.3 on 2022-04-18 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('vote', '0002_delete_vote'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replied_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActionType',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
