# Generated by Django 4.0.3 on 2022-04-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
